package com.guidopierri.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


/*

	*Choose a web framework: There are many web frameworks available for Java, such as Spring, Jersey, or Spark. Choose
 	a framework that you are comfortable with, or that fits the requirements of your project.

    *Create a controller class: In the web framework, create a controller class that handles HTTP requests for the noise
    generation endpoint. The controller class should contain a method that generates the noise and returns it as a
    response.

	*Map the endpoint URL: In the controller class, use the framework's annotations or configuration to map the noise
    generation method to a URL endpoint. For example, you might map the method to the URL "/api/noise".

    *Deploy the API: Once you have created the REST API, deploy it to a web server or hosting service. This will make
    the API accessible to your HTML project over the internet.

    *Call the API from the HTML project: In the HTML project, use JavaScript or another programming language to send an
    HTTP request to the noise generation endpoint URL. The response from the API will contain the noise generated by
    the Java program, which you can then use to modify your HTML page.*/
@SpringBootApplication
public class ApiApplication {

	public static void main(String[] args) {
		SpringApplication.run(ApiApplication.class, args);
	}

}
